### ISSUE TITLE
Complete fail, very obscure

### ISSUE THREAD

**Issue by nickveenhof** [baliame/ramldocgen#2]
```
nick.veenhof@nick-macbook:doc/raml$ ramldocgen generate api.raml index.html
Traceback (most recent call last):
  File "/usr/local/bin/ramldocgen", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/ramldocgen/ramldocgen.py", line 12, in generate
    g = Generator(infile)
  File "/usr/local/lib/python3.5/site-packages/ramldocgen/generator.py", line 241, in __init__
    self.raml = ramlparser.load(file)
  File "/usr/local/lib/python3.5/site-packages/pyraml/parser.py", line 147, in load
    return parse(c, relative_path)
  File "/usr/local/lib/python3.5/site-packages/pyraml/parser.py", line 197, in parse
    'traits', RamlRoot.traits)
  File "/usr/local/lib/python3.5/site-packages/pyraml/parser.py", line 104, in get_property_with_schema
    return property_schema.to_python(property_value)
  File "/usr/local/lib/python3.5/site-packages/pyraml/fields.py", line 343, in to_python
    for key, val in item.items()])
  File "/usr/local/lib/python3.5/site-packages/pyraml/fields.py", line 343, in <listcomp>
    for key, val in item.items()])
  File "/usr/local/lib/python3.5/site-packages/pyraml/fields.py", line 443, in to_python
    value, self.ref_class))
ValueError: 'usage: Apply this to any method that allows paging\ndescription: This API endpoint allows paging.\nqueryParameters:\n  start:\n    description: |\n      Where to start from. Eg if you have 20 items, and you fill in 10\n      as your start number, it will give you all the items from 10\n      till 19 if the amount of items you request is 10.\n    type: number\n    default: "0"\n  rows:\n    description: Amount of items to return\n    type: number\n    default: "10"' expected to be <class 'pyraml.entities.RamlTrait'> or dict
```

Not sure what this even means. I guess I should dig into the code but I really don't want to yet... Can we add some tests first please?

**Comment by cpliakas** [comment]
Thanks for the feedback. Contributions welcome, as is continuing to use the raml2html tool.

**Comment by baliame** [comment]
It seems the pyraml-parser cannot parse your raml properly. I suggest linting your raml and if you're certain it is correct, [taking it up with them](https://github.com/an2deg/pyraml-parser).

**Comment by baliame** [comment]
On closer inspection, they only seem to support RAML 0.8 officially, and [so does the alternative](https://github.com/spotify/ramlfications). Not a lot I can do unless someone contributes RAML 1.0 to any of these.

**Comment by baliame** [comment]
This does not seem to be well documented but the problem may lie in whether or not you're using the obscure syntax - I've noticed that RAML 0.8 exclusively only allows it.

By the obscure syntax, I mean doing:
```raml
foo:
  - bar:
     x: y
  - baz:
     x: y
```

instead of the more logical
```raml
foo:
  bar:
    x: y
  baz:
    x: y
```
